### ISSUE TITLE
ZkOn oracle doesn't work: Request.compile() depends on zkonProof

### ISSUE THREAD

**Issue by asimaranov** [ZKON-Network/zkapp#1]
ZkOn oracle doesn't work

New zkapp address - B62qopkkz2Xp4Rc37VGVorxaJqd89EwMEaqC7Ccw78BUUYuiwJVkJvQ
Ipfs hash - bafkreifl55k3prpumcnyrtrcaoqlbtkd45nczsfiztbgwowflchloeuc6y
Api - https://random-data-api.com/api/number/random_number

Worker error:
Error: Request.compile() depends on zkonProof, but we cannot find compilation output for zkonProof.

Seems that worker doesn't compile the internal contract proofs. 
Kindly asking to investigate and fix the issue as it's a blocker for the ZkNoid project in oracle integration

**Comment by Nytyr** [comment]
Closing the issue for now.

We already talked in private. 

When uploading the zkapp to IPFS all the dependencies has to be flatten inside the same file.
